#pragma once 
#ifndef MOUSEBUTTONCODES_H
#define MOUSEBUTTONCODES_H

//mousecodes from glfw3.h transcripted to enum
enum mouseButtonCodes {
	OT_MOUSE_BUTTON_1 = 0,
	OT_MOUSE_BUTTON_2,
	OT_MOUSE_BUTTON_3,
	OT_MOUSE_BUTTON_4,
	OT_MOUSE_BUTTON_5,
	OT_MOUSE_BUTTON_6,
	OT_MOUSE_BUTTON_7,
	OT_MOUSE_BUTTON_8,

	OT_MOUSE_BUTTON_LAST = OT_MOUSE_BUTTON_8,
	OT_MOUSE_BUTTON_LEFT = OT_MOUSE_BUTTON_1,
	OT_MOUSE_BUTTON_RIGHT = OT_MOUSE_BUTTON_2,
	OT_MOUSE_BUTTON_MIDDLE = OT_MOUSE_BUTTON_3
};
//Almost OG stolen glfw3.h mousecodes
/*
#define OT_MOUSE_BUTTON_1,
#define OT_MOUSE_BUTTON_2,
#define OT_MOUSE_BUTTON_3,
#define OT_MOUSE_BUTTON_4,
#define OT_MOUSE_BUTTON_5,
#define OT_MOUSE_BUTTON_6,
#define OT_MOUSE_BUTTON_7,
#define OT_MOUSE_BUTTON_8,
#define OT_MOUSE_BUTTON_LAST      OT_MOUSE_BUTTON_8
#define OT_MOUSE_BUTTON_LEFT      OT_MOUSE_BUTTON_1
#define OT_MOUSE_BUTTON_RIGHT     OT_MOUSE_BUTTON_2
#define OT_MOUSE_BUTTON_MIDDLE    OT_MOUSE_BUTTON_3
*/

#endif